name: Build and Deploy app to Azure Web app - Production

on:
  push:
    brnckes:
      - main
    workflow_dispatch:

jobs:

  build:
    name: Build and save to artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build Health-prescription-software-API/Health-prescription-software-API.csproj --configuration Release

      - name: Dontnet publish
        run: dotnet publish Health-prescription-software-API/Health-prescription-software-API.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./publish

  deploy:
    name: Deploy to Azure - production
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.WEB_APP_NAME }}
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  update-db:
    name: Apply migrations
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Update Database
        env:
          CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          dotnet ef database update --connection "${CONNECTION_STRING}"
        working-directory: Health-prescription-software-API
