name: Unit tests - services

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore Health-prescription-software-API

      - name: Build
        run: dotnet build Health-prescription-software-API/Health-prescription-software-API.csproj --no-restore

      - name: Test
        run: dotnet test Health-prescription-software-API.Services.Tests/Health-prescription-software-API.Services.Tests.csproj --no-build --verbosity normal
