name: Unit tests - services

on:
  pull_request:
	branches:
	  - main
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
	name: Unit tests
    runs-on: ubuntu-latest

	steps:
	  - name: Checkout repository
	    uses: actions/checkout@v3

	  - name: Setup .NET
		uses: actions/setup-dotnet@v3
		  with:
		  dotnet-version: 8.x
		
	  - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test Health-prescription-software-API.Services.Tests/Health-prescription-software-API.Services.Tests.csproj --no-build --verbosity normal